/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import ENUM.ClassesEnum;
import classes.Funcionario;
import classes.*;
import javax.swing.table.DefaultTableModel;
import persistencia.*;

/**
 *
 * @author watla
 */
public class Tela extends javax.swing.JFrame {

    Funcionario funcionario = null;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public void limpar() {
        jTextFieldHoras.setText("");
        jTextFieldSalario.setText("");
        jTextFieldSalarioSoma.setText("");
        jTextFieldSomaHoras.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSomaHoras = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneSAIDA = new javax.swing.JTextPane();
        jTextFieldSalarioSoma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFuncionaios = new javax.swing.JComboBox<>();
        jButtoneXECUTAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HORAS");

        jLabel2.setText("SALARIO");

        jLabel3.setText("+");

        jScrollPane1.setViewportView(jTextPaneSAIDA);

        jLabel4.setText("+");

        jComboBoxFuncionaios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAFETÃO", "PROFESSOR", "PROGRAMADOR" }));

        jButtoneXECUTAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtoneXECUTAR.setText("SOMA");
        jButtoneXECUTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneXECUTARActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "HORAS", "SALARIO"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFuncionaios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtoneXECUTAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldHoras)
                                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSomaHoras)
                                    .addComponent(jTextFieldSalarioSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jComboBoxFuncionaios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSomaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSalarioSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtoneXECUTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoneXECUTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneXECUTARActionPerformed
        String saida;
        SomaHoras somahoras = new SomaHoras();
        SomaSalario somasalario = new SomaSalario();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        double somaHoras = 0, somaSalario = 0;
        if (jComboBoxFuncionaios.getSelectedItem().equals("PROGRAMADOR")) {
            funcionario = FabricaDeObjetos.getTipoDeFuncionario(ClassesEnum.getProgramador());
            funcionario.setHorasTrabalhadas(Double.parseDouble(jTextFieldHoras.getText()));
            funcionario.setSalario(Double.parseDouble(jTextFieldSalario.getText()));
            //soma
            somaSalario = somasalario.objetoSoma(funcionario, Double.parseDouble(jTextFieldSalarioSoma.getText()));
            somaHoras = somahoras.objetoSoma(funcionario, Double.parseDouble(jTextFieldSomaHoras.getText()));
            //saida
            saida = "" + somaSalario + "\n" + somaHoras;
            jTextPaneSAIDA.setText(saida);
            Object[] dados = {ClassesEnum.getProgramador().toString().toUpperCase(), somaHoras, somaSalario};
            model.addRow(dados);
        }
        if (jComboBoxFuncionaios.getSelectedItem().equals("PROFESSOR")) {
            funcionario = FabricaDeObjetos.getTipoDeFuncionario(ClassesEnum.getProgramador());
            funcionario.setHorasTrabalhadas(Double.parseDouble(jTextFieldHoras.getText()));
            funcionario.setSalario(Double.parseDouble(jTextFieldSalario.getText()));
            //soma
            somaSalario = somasalario.objetoSoma(funcionario, Double.parseDouble(jTextFieldSalarioSoma.getText()));
            somaHoras = somahoras.objetoSoma(funcionario, Double.parseDouble(jTextFieldSomaHoras.getText()));
            //saida
            saida = "" + somaSalario + "\n" + somaHoras;
            jTextPaneSAIDA.setText(saida);
            Object[] dados = {"PROFESSOR", somaHoras, somaSalario};
            model.addRow(dados);
        }
        if (jComboBoxFuncionaios.getSelectedItem().equals("CAFETÃO")) {
            funcionario = FabricaDeObjetos.getTipoDeFuncionario(ClassesEnum.getProgramador());
            funcionario.setHorasTrabalhadas(Double.parseDouble(jTextFieldHoras.getText()));
            funcionario.setSalario(Double.parseDouble(jTextFieldSalario.getText()));
            //soma
            somaSalario = somasalario.objetoSoma(funcionario, Double.parseDouble(jTextFieldSalarioSoma.getText()));
            somaHoras = somahoras.objetoSoma(funcionario, Double.parseDouble(jTextFieldSomaHoras.getText()));
            //saida
            saida = "" + somaSalario + "\n" + somaHoras;
            jTextPaneSAIDA.setText(saida);
            Object[] dados = {"CAFETÃO", somaHoras, somaSalario};
            model.addRow(dados);
        }
        limpar();
    }//GEN-LAST:event_jButtoneXECUTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoneXECUTAR;
    private javax.swing.JComboBox<String> jComboBoxFuncionaios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSalarioSoma;
    private javax.swing.JTextField jTextFieldSomaHoras;
    private javax.swing.JTextPane jTextPaneSAIDA;
    // End of variables declaration//GEN-END:variables
}
